homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 49
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  external_url: https://hassio.hellstrom.space
  internal_url: http://192.168.1.195:8123
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - "/share/cameras"
# Show links to resources in log and frontend
#introduction:

script: !include_dir_merge_named scripts/

# Enables the frontend
frontend:
  themes: !include_dir_named themes
# Enables configuration UI
config:

system_health:

http:
  #  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 7
  use_x_forwarded_for: False
  trusted_proxies: !secret hassioip

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery: # Set this on to discover new devices. I have it off to make system more responsive plus security reasons

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Stream settings
stream:

recorder:
  purge_interval: 1
  purge_keep_days: 7
  db_url: !secret maria_db_url
  include:
    domains:
      - climate
    entities:
      - input_select.house_mode_select
      - media_player.melkers_tv
      - media_player.tv_nere
      - media_player.shield_tv
      # tracking
      - device_tracker.elin_presence
      - device_tracker.tomas_presence
      - device_tracker.melker_presence
      - device_tracker.sally_presence
      - sensor.occupancy

      # sensors of interest
      - sensor.utetemp_temperature
      - sensor.utetemp_humidity
      - sensor.temp_outside
      - sensor.frysnere_temperature #Frys nere
      - sensor.kok_frys_temp
      - sensor.sovrum_temp
      - sensor.vardagsrum_temp
      - sensor.sallys_rum_temp
      - sensor.melkers_rum_temp
      - sensor.hobbyrum_temp
      - binary_sensor.hall_dorr
      - switch.computer_tomas
      - remote.tvrummet
      # nuc stats
      - sensor.memory_use_percent
      - sensor.processor_use
      - binary_sensor.wash_mashine

      - switch.motorvarmare_hoger
      - sensor.light_outside

logger:
  default: info
  #logs:
  #   homeassistant.components.websocket_api: debug
  #   aiohttp: debug
  #  pydeconz: debug
  #  homeassistant.components.deconz: debug
  #homeassistant.components.scrape: debug
# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  username: !secret influx_username
  password: !secret influx_password
  include:
    entities:
      - input_select.house_mode_select
      - media_player.melkers_tv
      - media_player.shield_tv

      # tracking
      - device_tracker.elin_presence
      - device_tracker.tomas_presence
      - device_tracker.melker_presence
      - device_tracker.sally_presence

      - sensor.occupancy

      # sensors of interest
      - sensor.frysnere_temperature #Frys nere
      - binary_sensor.hall_dorr
      - switch.computer_tomas
      - remote.tvrummet
      # nuc stats
      - sensor.memory_use_percent
      - sensor.processor_use
      - binary_sensor.wash_mashine
      # Temperatures
      - sensor.hobbyrum_temp
      - sensor.kok_frys_temp
      - sensor.melkers_rum_temp
      - sensor.sallys_rum_temp
      - sensor.sovrum_temp
      - sensor.temp_outside
      - sensor.light_outside
      - sensor.vardagsrum_temp
      - switch.motorvarmare_hoger
# Enables  map showing the location of tracked devices
map:

mobile_app:

# sensor:
#   - platform: time_date
#   - platform: scrape
#     name: spot_price_sundsvall
#     resource: https://elen.nu/timpriser-pa-el-for-elomrade-se2-sundsvall
#     select: ".elspot-area-price strong"
#     value_template: '{{ ((value.split(" ")[0]) | replace (",", ".")) }}'
#     unit_of_measurement: "öre/kWh"
#     headers:
#       User-Agent: Mozilla/5.0
# Text to speech
tts:
  # - platform: google_cloud
  #   key_file: googlecloud.json
  #   language: sv-SE
  #   voice: sv-SE-Wavenet-A
  # pitch: -2
  #speed: 0.97
  - platform: google_translate
    service_name: google_cloud_say
    language: "sv"
    # cache: false
    # time_memory: 600
    base_url: http://192.168.1.7:8123

hassio:

lovelace:
  mode: yaml
  resources:
    - url: /local/custom_cards/custom-cards.js?v=1.106
      type: module
    - url: /hacsfiles/canvas-gauge-card/canvas-gauge-card.js?v=0.0.21
      type: module
    # - url: /local/custom_cards/mini-graph-card-bundle.js?v=0.2.4
    #   type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.0.1
      type: module
    # - url: /local/custom_cards/smhi-forecast-card.js?v=0.0.26
    #   type: module
    - url: /hacsfiles/krisinfo-card/krisinfo-card.js
      type: js
    # - url: /community_plugin/weather-card/weather-card.js?v1.0
    #   type: js
    - url: /hacsfiles/weather-card-mod/weather-card-mod.js?v0.7
      type: module
    # - url: /local/custom_cards/card-tools.js?v1.1
    #   type: js
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: js
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: js
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module

# hacs:
#   token: !secret github_token_hacs

person:
  - name: Tomas
    id: tomastracker
    device_trackers:
      - device_tracker.tomas_presence
  - name: Elin
    id: elintracker
    device_trackers:
      - device_tracker.elin_presence
  - name: Sally
    id: sallytracker
    device_trackers:
      - device_tracker.sally_presence
  - name: Melker
    id: melkertracker
    device_trackers:
      - device_tracker.melker_presence

# mqtt:
#   broker: !secret mqqtt_broker
#   discovery: false
#   discovery_prefix: homeassistant
#   username: !secret mqtt_user
#   password: !secret mqtt_password

# netdaemon:
#cloud:

# zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
