#Determine the status of the house to control depending on day, night, evening and morgnin

input_select:
  house_mode_select:
    name: Husstatus
    options:
      - Dag
      - Natt
      - Kväll
      - Morgon


sensor:
  - platform: template
    sensors:
      house_mode:
        value_template: '{{ states.input_select.house_mode_select.state }}'
        friendly_name: 'Hus status'

script:
  setnightmode:
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.house_mode_select
          option:  "Natt"          

