
# The heater it self is the "switch.motorvarmare"

# To set the hour and minutes of departure
input_number:
  car_heater_dep_time_hour:
    name: Timmar
    icon: mdi:timer
    initial: 07
    min: 0
    max: 23
    step: 1

  car_heater_dep_time_minutes:
    name: Minuter
    icon: mdi:timer
    initial: 15
    min: 0
    max: 55
    step: 5

input_boolean:
  schedule_on_weekends:
    name: "Kör på helger"
    initial: off
    
sensor:
  - platform: template
    sensors:
      car_departure_time:
        friendly_name: 'Avresetid bil'
        value_template: '{% if states.input_number.car_heater_dep_time_hour.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_number.car_heater_dep_time_hour.state|round(0)|string }}:{% if states.input_number.car_heater_dep_time_minutes.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_number.car_heater_dep_time_minutes.state|round(0)|string }}'
        # entity_id:
        #  - input_number.heater_ak_minutes
        #  - input_number.heater_ak_hour

