# Sundbyberg

POST https://webapp.ftiab.se/Code/Ajax/StationHandler.aspx/GetStationsByMunicipality HTTP/1.1
content-type: application/json

{
    "municipalityId":"10604"
}


# Sundsvall
POST https://webapp.ftiab.se/Code/Ajax/StationHandler.aspx/GetStationsByMunicipality HTTP/1.1
content-type: application/json

{
    "municipalityId":"12281"
}

# Sundbyberg

POST https://webapp.ftiab.se/Code/Ajax/StationHandler.aspx/GetStationsByMunicipality HTTP/1.1
content-type: application/json

{
    "municipalityId":"10183"
}






